---
- hosts: wordpress
  become: yes  
  vars_files:
    - vars/mysql.yml
  tasks:

    #PHP 7.4 Prerequisites in Ubuntu
    - name: Install Software Properties Common
      apt:
        name: software-properties-common
        state: present

    - name: Add PHP 7.4 Repo 
      apt_repository:
        repo: 'ppa:ondrej/php'
        state: present

    - name: apt update after the repo addition
      apt:
        update_cache: yes

    # Prerequisites Installation
    - name: Install LAMP Packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: ['apache2','php7.4', 'php7.4-mysql', 'libapache2-mod-php7.4']

    - name: Install PHP Extensions
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'php7.4-curl', 'php7.4-gd', 'php7.4-mbstring', 'php7.4-xml', 'php7.4-xmlrpc', 'php7.4-soap', 'php7.4-intl', 'php7.4-zip' ]

  # Apache Configuration
    - name: Delete the index.html file
      file:
        path: "/var/www/html/index.html"
        state: absent

  # Firewall Configuration
    - name: "UFW - Allow HTTP on port 80"
      ufw:
        rule: allow
        port: "80"
        proto: tcp

  # WordPress Configuration
    - name: Download and unpack latest WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/html"
        remote_src: yes

    - name: Move Wordpress Directory contents 
      command: mv /var/www/html/wordpress/* /var/www/html/

    - name: Set ownership
      file:
        path: "/var/www/html"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data

    - name: Set permissions for directories
      shell: "/usr/bin/find /var/www/html/ -type d -exec chmod 755 {} \\;"

    - name: Set permissions for files
      shell: "/usr/bin/find /var/www/html/ -type f -exec chmod 644 {} \\;"

    - name: Set up wp-config
      template:
        src: "files/wp-config.php.j2"
        dest: "/var/www/html/wp-config.php"
      notify: Restart Apache

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted