---
- hosts: mysql
  become: yes  
  vars_files:
    - vars/mysql.yml
  tasks:
    # Prerequisites Installation
    - name: Install MySQL Server Packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: ['mysql-server', 'python3-pymysql']

  # MySQL Configuration
    - name: Set the root password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Remove all anonymous user accounts
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Remove the MySQL test database
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Creates database for WordPress
      mysql_db:
        name: "{{ mysql_wordpress_db }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create MySQL user for WordPress
      mysql_user:
        name: "{{ mysql_wordpress_user }}"
        password: "{{ mysql_wordpress_password }}"
        priv: "{{ mysql_wordpress_db }}.*:ALL"
        host: "%"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Comment out bind address in MySQL Config
      replace:
        dest:  /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        replace: '#bind-address'

    - name: Restart the MySQL Service
      service:
        name: mysql
        state: restarted

  # Firewall Configuration
    - name: "UFW - Allow MYSQL on port 3306"
      ufw:
        rule: allow
        port: "3306"
        proto: tcp
